//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendasDF.RS_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RS_WS.CalculosWSSoap")]
    public interface CalculosWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubBronce", ReplyAction="*")]
        double clubBronce(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubBronce", ReplyAction="*")]
        System.Threading.Tasks.Task<double> clubBronceAsync(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubOro", ReplyAction="*")]
        double clubOro(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubOro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> clubOroAsync(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubDiamante", ReplyAction="*")]
        double clubDiamante(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubDiamante", ReplyAction="*")]
        System.Threading.Tasks.Task<double> clubDiamanteAsync(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubPlatino", ReplyAction="*")]
        double clubPlatino(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clubPlatino", ReplyAction="*")]
        System.Threading.Tasks.Task<double> clubPlatinoAsync(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sinConvenio", ReplyAction="*")]
        double sinConvenio(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sinConvenio", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sinConvenioAsync(int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/horasExtra", ReplyAction="*")]
        double horasExtra(int horasTrabajadas, int valorHora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/horasExtra", ReplyAction="*")]
        System.Threading.Tasks.Task<double> horasExtraAsync(int horasTrabajadas, int valorHora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculosWSSoapChannel : TiendasDF.RS_WS.CalculosWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculosWSSoapClient : System.ServiceModel.ClientBase<TiendasDF.RS_WS.CalculosWSSoap>, TiendasDF.RS_WS.CalculosWSSoap {
        
        public CalculosWSSoapClient() {
        }
        
        public CalculosWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculosWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculosWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double clubBronce(int precio) {
            return base.Channel.clubBronce(precio);
        }
        
        public System.Threading.Tasks.Task<double> clubBronceAsync(int precio) {
            return base.Channel.clubBronceAsync(precio);
        }
        
        public double clubOro(int precio) {
            return base.Channel.clubOro(precio);
        }
        
        public System.Threading.Tasks.Task<double> clubOroAsync(int precio) {
            return base.Channel.clubOroAsync(precio);
        }
        
        public double clubDiamante(int precio) {
            return base.Channel.clubDiamante(precio);
        }
        
        public System.Threading.Tasks.Task<double> clubDiamanteAsync(int precio) {
            return base.Channel.clubDiamanteAsync(precio);
        }
        
        public double clubPlatino(int precio) {
            return base.Channel.clubPlatino(precio);
        }
        
        public System.Threading.Tasks.Task<double> clubPlatinoAsync(int precio) {
            return base.Channel.clubPlatinoAsync(precio);
        }
        
        public double sinConvenio(int precio) {
            return base.Channel.sinConvenio(precio);
        }
        
        public System.Threading.Tasks.Task<double> sinConvenioAsync(int precio) {
            return base.Channel.sinConvenioAsync(precio);
        }
        
        public double horasExtra(int horasTrabajadas, int valorHora) {
            return base.Channel.horasExtra(horasTrabajadas, valorHora);
        }
        
        public System.Threading.Tasks.Task<double> horasExtraAsync(int horasTrabajadas, int valorHora) {
            return base.Channel.horasExtraAsync(horasTrabajadas, valorHora);
        }
    }
}
